name: OpenCCSharp WebApp on GitHub Pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"

jobs:
  github_pages_publish:
    name: "GitHub Pages Publish"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      OCCS_IS_CI_BUILD: true
      OCCS_WEBAPP_OUTPUT_DIR: _work/Publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
      - name: Build
        shell: pwsh
        run: "./OpenCCSharp.WebApp.CI/Build.ps1 -Configuration Release -OutputDir ${{ env.OCCS_WEBAPP_OUTPUT_DIR }}"
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "OpenCCSharp.WebApp-Output"
          path: ${{ env.OCCS_WEBAPP_OUTPUT_DIR }}/wwwroot
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: ${{ env.OCCS_WEBAPP_OUTPUT_DIR }}
